import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const page=readFileSync(new URL('../worker/page.html',import.meta.url),'utf8');
const source=page.slice(page.indexOf('function accountDayChange('),page.indexOf('function renderAccountDayChanges('));
const calculate=new Function(source+';return accountDayChange;')();
const now=Date.parse('2026-10-08T10:00:00+08:00');
const account={positions:[{symbol:'a',weight:.3},{symbol:'b',weight:.4}]};
const stocks=[{symbol:'a',quote:{change:2,time:'2026-10-08 09:59:00'}},{symbol:'b',quote:{change:-1,time:'2026-10-08 09:59:00'}}];
const priorChange=.3*2/102+.4*(-1)/99;
assert(Math.abs(calculate(account,stocks,now)-priorChange/(1-priorChange)*100)<1e-10);
const exactAccount={positions:[{symbol:'a',weight:30.6/100.2},{symbol:'b',weight:39.6/100.2}]};
assert(Math.abs(calculate(exactAccount,stocks,now)-.2)<1e-10,'Yesterday assets 100 includes cash 30, current assets 100.2');
assert(Math.abs(calculate({positions:[{symbol:'a',weight:81.6/101.6}]},stocks,now)-1.6)<1e-10,'Cash 20 remains in denominator');
assert.equal(calculate({positions:[{symbol:'a',weight:0}]},stocks,now),0);
assert.equal(calculate(account,stocks.map(s=>({...s,quote:{...s.quote,time:'2026-09-30 15:00:00'}})),now),null);
assert.equal(calculate(account,[stocks[0]],now),null);
assert.equal(calculate({positions:[{symbol:'a',weight:null}]},stocks,now),null);
assert.equal(calculate(account,stocks.map(s=>({...s,quote:{...s.quote,time:'2026-10-08 10:01:00'}})),now),null);
assert(page.includes('.day-gain{color:#ffd166}')&&page.includes('.day-loss{color:#6fb9ff}'));
console.log('PASS: account weight estimate, cash contribution, missing/old/future quotes, gold/blue colors');
